export const DEFAULT_CATEGORIES: { name: string; color: string }[] = [
  { name: "Food & Dining", color: "#e67c5a" },
  { name: "Restaurants", color: "#e68a4a" },
  { name: "Groceries", color: "#e68a3a" },
  { name: "Transportation", color: "#5a9de6" },
  { name: "Fuel", color: "#4a7de6" },
  { name: "Public Transit", color: "#3a5cc7" },
  { name: "Entertainment", color: "#a85ae6" },
  { name: "Streaming", color: "#8a4ae6" },
  { name: "Subscriptions", color: "#7a3ac7" },
  { name: "Health", color: "#3ab86a" },
  { name: "Pharmacy", color: "#2a9a5a" },
  { name: "Education", color: "#e6c83a" },
  { name: "Clothing", color: "#e65a8a" },
  { name: "Home", color: "#e6a83a" },
  { name: "Investments", color: "#22c55e" },
  { name: "Incomes", color: "#2a9a6a" },
  { name: "Invoice Payment", color: "#e65a5a" },
  { name: "Other", color: "#ef4444" },
];
